java server:
    port: 80

app:
    logging-to: console # options are: console/file
    drone:
        video-ws-endpoint: /videofeed
        video-server-port: 1313
        drone-id-length: 1 # one bite size



logging:
    level:
        org.springframework: INFO
        com.example.demo: DEBUG

